-- ==========================================================
-- MPI LINGKARAN - SUPABASE DATABASE SETUP
-- Jalankan seluruh file ini di Supabase SQL Editor.
-- ==========================================================

-- 1) Tabel state/progres per anonymous authenticated user
create table if not exists public.student_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  student_name text not null default '',
  class_name text not null default '' check (class_name in ('', '9A', '9B')),
  app_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- 2) Tabel hasil evaluasi. Satu attempt_id = satu percobaan evaluasi.
create table if not exists public.evaluation_results (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  student_name text not null,
  class_name text not null check (class_name in ('9A', '9B')),
  score integer not null check (score between 0 and 100),
  category text not null,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_evaluation_results_user_id
  on public.evaluation_results(user_id);

create index if not exists idx_evaluation_results_class_name
  on public.evaluation_results(class_name);

create index if not exists idx_evaluation_results_created_at
  on public.evaluation_results(created_at desc);

-- 3) Trigger updated_at
create or replace function public.set_student_state_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_student_state_updated_at on public.student_state;
create trigger trg_student_state_updated_at
before update on public.student_state
for each row
execute function public.set_student_state_updated_at();

-- 4) Aktifkan RLS
alter table public.student_state enable row level security;
alter table public.evaluation_results enable row level security;

-- 5) Least privilege grants.
-- Anonymous Auth user dari Supabase memakai role "authenticated".
revoke all on table public.student_state from anon, authenticated;
revoke all on table public.evaluation_results from anon, authenticated;

grant select, insert, update on table public.student_state to authenticated;
grant select, insert, update on table public.evaluation_results to authenticated;

-- Sequence identity dibutuhkan untuk INSERT ke evaluation_results.
grant usage, select on sequence public.evaluation_results_id_seq to authenticated;

-- 6) Hapus policy lama bila file dijalankan ulang
drop policy if exists "student_state_select_own" on public.student_state;
drop policy if exists "student_state_insert_own" on public.student_state;
drop policy if exists "student_state_update_own" on public.student_state;

drop policy if exists "evaluation_select_own" on public.evaluation_results;
drop policy if exists "evaluation_insert_own" on public.evaluation_results;
drop policy if exists "evaluation_update_own" on public.evaluation_results;

-- 7) RLS student_state: user hanya boleh melihat/menulis row miliknya
create policy "student_state_select_own"
on public.student_state
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "student_state_insert_own"
on public.student_state
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "student_state_update_own"
on public.student_state
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- 8) RLS evaluation_results: user hanya boleh melihat/menulis attempt miliknya
create policy "evaluation_select_own"
on public.evaluation_results
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "evaluation_insert_own"
on public.evaluation_results
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "evaluation_update_own"
on public.evaluation_results
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- ==========================================================
-- VERIFIKASI MANUAL (opsional)
-- Setelah siswa memakai aplikasi, guru/admin bisa melihat data
-- melalui Supabase Dashboard > Table Editor > evaluation_results.
-- ==========================================================
